apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: {{buildId | int}}
  labels:
    app: image-process
  name: image-process
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: image-process
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: image-process
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      containers:
      - image: {{imageRegistry}}:{{buildId}}
        imagePullPolicy: IfNotPresent
        name: image-process
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-process
  name: image-process
  namespace: default
spec:
  ports:
  - name: image-process
    nodePort: 31704
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: image-process
  type: NodePort
